CalculatorProject/Controllers/CalcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CalculatorProject.Manager;
using CalculatorProject.Classes;

namespace CalculatorProject.Controllers
{
    public class CalcController : Controller
    {
        private ICalcManager _CalcManager;
        public CalcController(ICalcManager CalcManager)
        {
            _CalcManager= CalcManager;
        }

        public ViewResult MainPage()
        {
            return View();
        }

        
        
        public ViewResult Calcpage()
        {
            return View();
        }

        public ViewResult Lab1Page()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Submit(string operations, string base_num)
        {
            operations = operations.Replace(" ", String.Empty);
            String[] stringSeparators = new string[] { "+", "-", "*", "/", "%", "^" };
            String[] numbers = operations.Split(stringSeparators, StringSplitOptions.None);
            String operation = operations.Replace(numbers[0], String.Empty);
            operation = operation.Replace(numbers[1], String.Empty);
            int basenum = 0;
            if (base_num != null)
            {
                basenum = Int32.Parse(base_num);
            }
            else { basenum = 10; }
            long[] temp_numbs = new long[2];

            temp_numbs[0] = BaseConvertation.ArbitraryToDecimalSystem(numbers[0],basenum);
            temp_numbs[1] = BaseConvertation.ArbitraryToDecimalSystem(numbers[1], basenum);
            long temp_res = 0;

            switch (operation)
            {
                case "+":
                    temp_res = long.Parse(Convert.ToString(_CalcManager.Sum(temp_numbs[0], temp_numbs[1])));
                    break;

                case"-":
                    temp_res = long.Parse(Convert.ToString(_CalcManager.Subtraction(temp_numbs[0], temp_numbs[1])));
                    break;

                case "*":
                    temp_res = long.Parse(Convert.ToString(_CalcManager.Multip(temp_numbs[0], temp_numbs[1])));
                    break;

                case "/":
                    temp_res = long.Parse(Convert.ToString(_CalcManager.Div(temp_numbs[0], temp_numbs[1])));
                    break;

                case "^":
                    temp_res = long.Parse(Convert.ToString(_CalcManager.Degree(temp_numbs[0], temp_numbs[1])));
                    break;

                case "%":
                    temp_res = long.Parse(Convert.ToString(_CalcManager.Mod(temp_numbs[0], temp_numbs[1])));
                    break;

            }
            String[] model = new String[5];
            model[0] = numbers[0];
            model[1] = operation;
            model[2] = numbers[1];
            model[3] = BaseConvertation.DecimalToArbitrarySystem(temp_res, basenum);
            model[4] = base_num;

            try
            {
                return View("Calcpage", model);
                //return RedirectToAction(nameof(Computation));
            }
            catch 
            {
                return RedirectToAction(nameof(Calcpage));
            }
        }
    }
}

CalculatorProject/Controllers/LabController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CalculatorProject.Manager;

namespace CalculatorProject.Controllers
{
    public class LabController : Controller
    {
        private ICalcManager _calculatorManager;
        public LabController(ICalcManager calculatorManager)
        {
            _calculatorManager = calculatorManager;
        }
        public IActionResult Lab1Page()
        {
            Random rnd = new Random();
            string[] model = new string[1];
            for (int i = 0; i < 15; i++)
            {
                model[0] += Convert.ToString(rnd.Next(-10, 20));
                if (i != 14) model[0] += " ";
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Mult(string numstring)
        {
            string[] model = new string[2];
            model[0] = numstring;

            try
            {

                string[] numarray = numstring.Split(' ', StringSplitOptions.RemoveEmptyEntries);
                double[] numbers = new double[numarray.Length];
                for (int i = 0; i < numarray.Length; i++)
                {
                    numbers[i] = Convert.ToDouble(numarray[i]);
                }

                model[1] = Convert.ToString(this._calculatorManager.ArrayMultip(numbers));
            }
            catch (ArgumentException e) when (e.ParamName == "numbers")
            {
                model[1] = e.Message;
            }
            catch (FormatException)
            {
                model[1] = "Неправильно введено какое-то число.";
            }
            catch (Exception)
            {
                model[1] = "Неправильно введено выражение.";
            }

            return View("Lab1Page", model);
        }
    }
}

CalculatorProject/Views/Calc/Calcpage.cshtml
@model string[]

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Calculator</title>
    <script>
        var a = 0;
        function addText(val) {
            document.getElementById("result").value += val;
        }
        function dis(val) {
            document.getElementById("bn").value += val;
        }
       
    </script>

</head>
<body>
   
   

    <h1 style="color:#57ab9b" class="Calc">Калькулятор</h1>
    <img src="https://i.gifer.com/ICU.gif" />
    <img style="position:absolute;right:8px" src="https://i.gifer.com/ICU.gif" />

    <div align="center" class="btn-cont">
        <ul class="hr">
            <li> <button class="btn" type="button" onclick="location.href='@Url.Action("MainPage", "Calc")'">На главную</button></li>
            <li>  <button class="btn" type="button" onclick="location.href='@Url.Action("Lab1Page", "Lab")'">Работа с массивом</button></li>

        </ul>
    </div>
    @using (Html.BeginForm("Submit", "Calc"))
    {
<div align="center">
    <label style="background-color:#DCDCDC;font-weight:bold; font-size:14pt;">Выберите систему счисления</label>
    <table style="background-color:#DCDCDC">
        <tr>
            <td><input class="calcbtn" type="button" value="8" onclick="dis('8')" /></td>
            <td><input class="calcbtn" type="button" value="10" onclick="dis('10')" /></td>
            <td><input class="calcbtn" type="button" value="16" onclick="dis('16')" /></td>
            <td><input type="text" id="bn" name="base_num" size="10" /></td>
        </tr>
    </table>
    <table border="0" style="background-color:#DCDCDC">

        <tr>
            <td colspan="3"><input id="result" type="text" name="operations" size="10" /></td>
            <td><input class="calcbtn" type="submit" value="=" /></td>
        </tr>
        <tr>
            <td colspan="1"><input class="calcbtn" type="button" onclick="addText('7')" value="7" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('8')" value="8" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('9')" value="9" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('+')" value="+" /></td>
        </tr>
        <tr>
            <td colspan="1"><input class="calcbtn" type="button" onclick="addText('4')" value="4" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('5')" value="5" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('6')" value="6" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('-')" value="-" /></td>
        </tr>
        <tr>
            <td colspan="1"><input class="calcbtn" type="button" onclick="addText('1')" value="1" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('2')" value="2" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('3')" value="3" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('*')" value="*" /></td>
        </tr>
        <tr>
            <td><input class="calcbtn" type="button" onclick="addText('A')" value="A" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('B')" value="B" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('C')" value="C" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('D')" value="D" /></td>
        </tr>
        <tr>
            <td><input class="calcbtn" type="button" onclick="addText('E')" value="E" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('F')" value="F" /></td>
        </tr>
        <tr>
            <td colspan="1"><input class="calcbtn" type="button" onclick="addText('/')" value="/" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('0')" value="0" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('^')" value="^" /></td>
            <td><input class="calcbtn" type="button" onclick="addText('%')" value="%" /></td>
        </tr>

    </table>
    <label  style="font-size:14pt;background-color:#DCDCDC">ответ:</label>
    @{
        if (Model != null)
        {
            if (Model.Length > 0)
            {
                <label style="font-size:14pt;background-color:#DCDCDC"> @Model[3]</label>


            }

        }
    }

</div>
    }

   

</body>
            </html>
            <style>
                .calcbtn {
                    background-color: #808080;
                    font-size:14pt;
                }
                .Calc {
                    font-family: 'Comic Sans MS';
                    text-align: center;
                    line-height: 1em;
                    color: #fff9d6;
                    font-weight: bold;
                    font-size: 75px;
                    text-shadow: 0px 0px 0 rgb(231,231,231),1px 1px 0 rgb(216,216,216),2px 2px 0 rgb(202,202,202),3px 3px 0 rgb(187,187,187),4px 4px 0 rgb(173,173,173),5px 5px 0 rgb(158,158,158), 6px 6px 0 rgb(144,144,144),7px 7px 6px rgba(0,0,0,0.6),7px 7px 1px rgba(0,0,0,0.5),0px 0px 6px rgba(0,0,0,.2);
                }
                body {
                    background-image: url('https://sun9-10.userapi.com/c857324/v857324602/16d271/UTA9x3ci0EU.jpg');
                    background-repeat: no-repeat;
                    background-color: lightskyblue;
                    background-position: 50% 10%;
                }
                .btn {
                    font-size: 28px;
                    font-family: Tahoma;
                    color: #c2dfe2;
                    background-color: #57ab9b;
                    font-weight: bold;
                }
                .btn-cont {
                    position: absolute;
                    left: 35%;
                    bottom: 0;
                }
                ul.hr li{
                    display:inline;

                }

            </style>

CalculatorProject/Views/Calc/MainPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Calculator</title>
</head>
<body>
    <h1 style="color:#57ab9b" class="Logo">Проект Александрова Михаила</h1>

    <img src="https://i.gifer.com/ICU.gif" />
    <img style="position:absolute;right:8px" src="https://i.gifer.com/ICU.gif" />
    <div align="center" class="btn-cont">
        <ul class="hr">
            <li> <button class="btn" type="button" onclick="location.href='@Url.Action("Lab1Page", "Lab")'">Работа с массивом</button></li>
            <li> <button class="btn" type="button" onclick="location.href='@Url.Action("Calcpage", "Calc")'">Калькулятор</button></li>

        </ul>
    </div>
</body>

</html>

<style>
    .Logo {
        font-family: 'Comic Sans MS';
        text-align: center;
        line-height: 1em;
        color: #fff9d6;
        font-weight: bold;
        font-size: 75px;
        text-shadow: 0px 0px 0 rgb(231,231,231),1px 1px 0 rgb(216,216,216),2px 2px 0 rgb(202,202,202),3px 3px 0 rgb(187,187,187),4px 4px 0 rgb(173,173,173),5px 5px 0 rgb(158,158,158), 6px 6px 0 rgb(144,144,144),7px 7px 6px rgba(0,0,0,0.6),7px 7px 1px rgba(0,0,0,0.5),0px 0px 6px rgba(0,0,0,.2);
    }
    body {
        background-image: url('https://sun9-10.userapi.com/c857324/v857324602/16d271/UTA9x3ci0EU.jpg');
        background-repeat: no-repeat;
        background-color:lightskyblue;
        background-position:50% 10%;
    }
    .btn {
        font-size: 28px;
        font-family: Tahoma;
        color: #c2dfe2;
        background-color: #57ab9b;
        font-weight: bold;
    }

    .btn-cont {
        position: absolute;
        left: 35%;
        bottom: 0;
    }

    ul.hr li {
        display: inline;
    }
</style>

CalculatorProject/Views/Lab/Lab1Page.cshtml
@model string[]
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Calculator</title>
</head>
<body>
    <h1 style="color:#57ab9b" class="Lab">Работа с массивом</h1>
    <img src="https://i.gifer.com/ICU.gif" />
    <img style="position:absolute;right:8px" src="https://i.gifer.com/ICU.gif" />

    @using (Html.BeginForm("Mult", "Lab"))
    {
<div align="center">
    <button class="btn1" type="button" onclick="location.href='@Url.Action("Lab1Page", "Lab")'">Сгенерировать</button><br />
    @if (Model != null)
    {
        <textarea name="numstring" rows="7" cols="40">@Model[0]</textarea><br />
    }


    <input type="submit" value="Посчитать" />
    <label style="background-color:#DCDCDC; font-weight:bold">Произведеие чисел больше 0 и меньше 54: </label>
    @{
        if (Model != null)
        {
            if (Model.Length > 1)
            {
        <label style="background-color:#DCDCDC"> @Model[1]</label>
            }
        }
    }
</div>
    }
    
    <footer style="position:fixed; height:50px; bottom:7px; left:39%;">
        <div align="center" class="btn-cont">
            <ul class="hr">
                <li><button class="btn" type="button" onclick="location.href='@Url.Action("MainPage", "Calc")'">На главную</button></li>
                <li><button class="btn" type="button" onclick="location.href='@Url.Action("Calcpage", "Calc")'">Калькулятор</button></li>


            </ul>
        </div>
    </footer>
</body>
</html>

<style>
    .Lab {
        font-family: 'Comic Sans MS';
        text-align: center;
        line-height: 1em;
        color: #fff9d6;
        font-weight: bold;
        font-size: 75px;
        text-shadow: 0px 0px 0 rgb(231,231,231),1px 1px 0 rgb(216,216,216),2px 2px 0 rgb(202,202,202),3px 3px 0 rgb(187,187,187),4px 4px 0 rgb(173,173,173),5px 5px 0 rgb(158,158,158), 6px 6px 0 rgb(144,144,144),7px 7px 6px rgba(0,0,0,0.6),7px 7px 1px rgba(0,0,0,0.5),0px 0px 6px rgba(0,0,0,.2);
    }

    body {
        background-image: url('https://sun9-10.userapi.com/c857324/v857324602/16d271/UTA9x3ci0EU.jpg');
        background-repeat: no-repeat;
        background-color: lightskyblue;
        background-position: 50% 10%;
    }
    .btn {
        font-size: 28px;
        font-family: Tahoma;
        color: #c2dfe2;
        background-color: #57ab9b;
        font-weight: bold;
    }

    /*  .btn-cont {
        margin: 0  auto;
        margin-bottom:0;
    }*/ 

    ul.hr li {
        display: inline;
    }
    
</style>